version: '3.8'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: mysql-srv
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "devbook"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - devbook

  app:
    container_name: devbook-api
    environment:
      API_PORTA: $API_PORTA
      BD_HOST: "mysqlsrv"
      BD_PORT: $BD_PORT
      DB_NOME: $DB_NOME
      DB_SENHA: $DB_SENHA
      DB_USUARIO: $DB_USUARIO
      SECRET_KEY: $SECRET_KEY
    build:
      context: bin/
    ports:
      - "3000:3000"
    networks:
      - devbook
    depends_on:
      - mysqlsrv

networks: 
  devbook:
    driver: bridge
